CREATE TABLE usuario (
	id_usuario INT AUTO_INCREMENT PRIMARY KEY,
	nome_usuario VARCHAR(30) NOT NULL UNIQUE,
	email VARCHAR(100) NOT NULL UNIQUE,
	senha VARCHAR(100) NOT NULL,
	nome VARCHAR(100) NOT NULL,
	cpf VARCHAR(11) NOT NULL UNIQUE,
	telefone VARCHAR(11),
	data_nascimento DATE,
	foto VARCHAR(255),
	data_criacao TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	ativo BOOLEAN DEFAULT TRUE,
	id_permissao INT NOT NULL,
	CONSTRAINT fk_usuario_permissao FOREIGN KEY (id_permissao) REFERENCES usuario(id_permissao),
);