CREATE TABLE campeonato (
	id_campeonato INT AUTO_INCREMENT PRIMARY KEY,
	codigo VARCHAR(10) NOT NULL UNIQUE,
	titulo VARCHAR(50) NOT NULL,
	descricao VARCHAR(255) NOT NULL,
	aposta VARCHAR(100),
	data_criacao TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	data_inicio TIMESTAMP NOT NULL,
	data_fim TIMESTAMP NOT NULL,
	limite_times INT NOT NULL,
	limite_participantes INT NOT NULL,
	ativo BOOLEAN DEFAULT TRUE,
	id_endereco INT NOT NULL,
	id_privacidade_campeonato INT NOT NULL,
	id_academico INT NOT NULL,
	id_modalidade_esportiva INT NOT NULL,
	id_situacao_campeonato INT NOT NULL,
	CONSTRAINT fk_campeonato_endereco FOREIGN KEY (id_endereco) REFERENCES endereco(id_endereco),
	CONSTRAINT fk_campeonato_privacidade_campeonato FOREIGN KEY (id_privacidade_campeonato) REFERENCES privacidade_campeonato(id_privacidade_campeonato),
	CONSTRAINT fk_campeonato_academico FOREIGN KEY (id_academico) REFERENCES academico(id_academico),
	CONSTRAINT fk_campeonato_modalidade_esportiva FOREIGN KEY (id_modalidade_esportiva) REFERENCES modalidade_esportiva(id_modalidade_esportiva),
	CONSTRAINT fk_campeonato_situacao_campeonato FOREIGN KEY (id_situacao_campeonato) REFERENCES situacao_campeonato(id_situacao_campeonato)
);