package com.sportfy.sportfy.enums;

public enum TipoPrivacidade {
    MOSTRAR_MODALIDADES_ESPORTIVAS,
    MOSTRAR_HISTORICO_CAMPEONATOS,
    MOSTRAR_ESTATISTICAS_MODALIDADES_ESPORTIVAS,
    MOSTRAR_CONQUISTAS,
}
